### ISSUE TITLE
Fonte dos dados

### ISSUE THREAD

**Issue by rodorgas** [GuiiHenriq/sp-covid19#2]
Qual a fonte dos dados? Sabe se ela ainda é atualizada? Pois no site consta atualização em 17/abril.

**Comment by GuiiHenriq** [comment]
> Qual a fonte dos dados? Sabe se ela ainda é atualizada? Pois no site consta atualização em 17/abril.

A fonte de dados se encontra no rodapé do site, estamos em constantes atualizações. Até o presente momento a Secretaria Municipal da Saúde não publicou um novo Boletim Semanal com os dados atualizados para os bairros de SP.

**Comment by rodorgas** [comment]
Puxa, que pena que a frequência de atualização não é maior. Obrigado!
